/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        background: '#fbf8ff',
        surface: '#fbf8ff',
        'surface-bright': '#fbf8ff',
        'surface-dim': '#dad9e3',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f4f2fd',
        'surface-container': '#eeedf7',
        'surface-container-high': '#e8e7f1',
        'surface-container-highest': '#e3e1ec',
        'surface-variant': '#e3e1ec',
        'surface-tint': '#a14000',
        'inverse-surface': '#2f3038',
        'inverse-on-surface': '#f1effa',
        'inverse-primary': '#ffb694',
        primary: {
          DEFAULT: '#a14000',
          50: '#fff7ed',
          100: '#ffedd5',
          200: '#fed7aa',
          300: '#fdba74',
          400: '#fb923c',
          500: '#f97316',
          600: '#ea580c',
          700: '#c2410c',
          800: '#9a3412',
          900: '#7c2d12',
        },
        'primary-container': '#f26b1d',
        'on-primary': '#ffffff',
        'on-primary-fixed': '#351000',
        'on-primary-fixed-variant': '#7b2f00',
        'primary-fixed': '#ffdbcc',
        'primary-fixed-dim': '#ffb694',
        'outline': '#8c7166',
        'outline-variant': '#e0c0b2',
        secondary: '#5f5e61',
        'secondary-container': '#e4e1e6',
        'on-secondary': '#ffffff',
        'on-secondary-fixed': '#1b1b1e',
        'on-secondary-fixed-variant': '#47464a',
        'secondary-fixed': '#e4e1e6',
        'secondary-fixed-dim': '#c8c5ca',
        tertiary: '#006398',
        'tertiary-container': '#009be9',
        'on-tertiary': '#ffffff',
        'on-tertiary-fixed': '#001d31',
        'on-tertiary-fixed-variant': '#004b73',
        'tertiary-fixed': '#cce5ff',
        'tertiary-fixed-dim': '#93ccff',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        'on-surface': '#1a1b22',
        'on-surface-variant': '#594237',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'section-gap-sm': '2rem',
        'topbar-height': '56px',
        'section-gap-lg': '3rem',
        'inset-md': '0.75rem',
        'inset-xl': '1.5rem',
        'inset-lg': '1rem',
        'card-padding': '1.5rem',
        'inset-xs': '0.25rem',
        'inset-sm': '0.5rem',
        'sidebar-width': '220px',
      },
      fontFamily: {
        'body-sm': ['Inter'],
        'label-md': ['Inter'],
        'body-md': ['Inter'],
        'headline-md': ['Inter'],
        'numeric-metric': ['Inter'],
        'headline-lg': ['Inter'],
        'label-sm': ['Inter'],
        'headline-sm': ['Inter'],
        'body-lg': ['Inter'],
        'display-lg': ['Inter'],
      },
      fontSize: {
        'body-sm': ['12px', { lineHeight: '16px', letterSpacing: '0', fontWeight: '400' }],
        'label-md': ['13px', { lineHeight: '18px', letterSpacing: '-0.005em', fontWeight: '500' }],
        'body-md': ['14px', { lineHeight: '20px', letterSpacing: '0', fontWeight: '400' }],
        'headline-md': ['20px', { lineHeight: '28px', letterSpacing: '-0.015em', fontWeight: '600' }],
        'numeric-metric': ['28px', { lineHeight: '32px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-lg': ['24px', { lineHeight: '32px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'label-sm': ['11px', { lineHeight: '14px', letterSpacing: '0.02em', fontWeight: '500' }],
        'headline-sm': ['16px', { lineHeight: '24px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', letterSpacing: '0', fontWeight: '400' }],
        'display-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.025em', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
}
